// <auto-generated />
using System;
using ERPlus.Modules.Identity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERPlus.Modules.Identity.Infrastructure.Data.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ERPlus.Modules.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("ERPlus.Modules.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleName", "Resource")
                        .IsUnique();

                    b.ToTable("role_permissions", "identity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "dashboard",
                            RoleName = "Operador Master"
                        },
                        new
                        {
                            Id = 2,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "agenda",
                            RoleName = "Operador Master"
                        },
                        new
                        {
                            Id = 3,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "contatos",
                            RoleName = "Operador Master"
                        },
                        new
                        {
                            Id = 4,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "financeiro",
                            RoleName = "Operador Master"
                        },
                        new
                        {
                            Id = 5,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "comercial",
                            RoleName = "Operador Master"
                        },
                        new
                        {
                            Id = 6,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "empreendimentos",
                            RoleName = "Operador Master"
                        },
                        new
                        {
                            Id = 7,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "producao",
                            RoleName = "Operador Master"
                        },
                        new
                        {
                            Id = 8,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "suporte",
                            RoleName = "Operador Master"
                        },
                        new
                        {
                            Id = 9,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "configuracoes",
                            RoleName = "Operador Master"
                        },
                        new
                        {
                            Id = 10,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "relatorios",
                            RoleName = "Operador Master"
                        },
                        new
                        {
                            Id = 11,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "dashboard",
                            RoleName = "Colaborador"
                        },
                        new
                        {
                            Id = 12,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "agenda",
                            RoleName = "Colaborador"
                        },
                        new
                        {
                            Id = 13,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "contatos",
                            RoleName = "Colaborador"
                        },
                        new
                        {
                            Id = 14,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "financeiro",
                            RoleName = "Colaborador"
                        },
                        new
                        {
                            Id = 15,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "comercial",
                            RoleName = "Colaborador"
                        },
                        new
                        {
                            Id = 16,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "empreendimentos",
                            RoleName = "Colaborador"
                        },
                        new
                        {
                            Id = 17,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "producao",
                            RoleName = "Colaborador"
                        },
                        new
                        {
                            Id = 18,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "suporte",
                            RoleName = "Colaborador"
                        },
                        new
                        {
                            Id = 19,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "configuracoes",
                            RoleName = "Colaborador"
                        },
                        new
                        {
                            Id = 20,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "relatorios",
                            RoleName = "Colaborador"
                        },
                        new
                        {
                            Id = 21,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "dashboard",
                            RoleName = "Visitante"
                        },
                        new
                        {
                            Id = 22,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "agenda",
                            RoleName = "Visitante"
                        },
                        new
                        {
                            Id = 23,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "contatos",
                            RoleName = "Visitante"
                        },
                        new
                        {
                            Id = 24,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "financeiro",
                            RoleName = "Visitante"
                        },
                        new
                        {
                            Id = 25,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "comercial",
                            RoleName = "Visitante"
                        },
                        new
                        {
                            Id = 26,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "empreendimentos",
                            RoleName = "Visitante"
                        },
                        new
                        {
                            Id = 27,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "producao",
                            RoleName = "Visitante"
                        },
                        new
                        {
                            Id = 28,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "suporte",
                            RoleName = "Visitante"
                        },
                        new
                        {
                            Id = 29,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "configuracoes",
                            RoleName = "Visitante"
                        },
                        new
                        {
                            Id = 30,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Resource = "relatorios",
                            RoleName = "Visitante"
                        });
                });

            modelBuilder.Entity("ERPlus.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("ERPlus.Modules.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ERPlus.Modules.Identity.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
